on:
    push:
        branches:
            - main
        # Sequence of patterns matched against refs/tags
        tags:
            - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Changelog 🗃
              uses: BobAnkh/auto-generate-changelog@master
              with:
                  REPO_NAME: 'bridge-core/editor'
                  ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  PATH: '/CHANGELOG.md'
                  COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
                  TYPE: 'feat:Features,fix:Bug Fixes,upd:Changes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
