name: Run Unit Tests

on:
    push:
        branches-ignore:
            - main

jobs:
    build:
        strategy:
            matrix:
                platform: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout 🛎
              uses: actions/checkout@v1
            - name: Setup Node.js 💻
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Run Tests 🧪
              run: |
                  npm install
                  npm run test
